language: objective-c

script: xcodebuild test -sdk iphonesimulator -project trackup.xcodeproj -scheme trackup-core -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' CODE_SIGNING_REQUIRED=NO
